nnoremap <SPACE> <Nop>
let mapleader=" "

" General
set nocompatible
set backspace=indent,eol,start
set clipboard=unnamedplus

" Visual
set bg=light
syntax on
set relativenumber
set number
set ruler
set showmode
set showcmd
set showmatch
set colorcolumn=80
set matchtime=2

" Tabs & Indentation
set tabstop=4
set shiftwidth=4

" Search settings
set ignorecase
set smartcase
set hlsearch
set incsearch

" Backup & Undo
set noswapfile
set nobackup

set undodir=~/.vim/undo-dir
set undofile

" Misc
set history=200
set display=truncate
filetype plugin indent on
set lazyredraw
set mouse=a
set scrolloff=8
set updatetime=50

" Remaps
nnoremap <Leader>o o<Esc>
nnoremap <Leader>O O<Esc>
inoremap jh <Esc>

